# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "event_participants", :force => true do |t|
    t.column "event_id", :integer
    t.column "rider_id", :integer
    t.column "horse_id", :integer
    t.column "result", :string
  end

  create_table "events", :force => true do |t|
    t.column "name", :string
    t.column "event_class", :string
    t.column "sponsor", :string
    t.column "sponsor2", :string
    t.column "sponsor3", :string
    t.column "fee", :integer
    t.column "cup", :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "description", :string
  end

  create_table "horses", :force => true do |t|
    t.column "owner_id", :integer
    t.column "name", :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
    t.column "number", :integer
  end

  create_table "owners", :force => true do |t|
    t.column "name", :string
    t.column "street1", :string
    t.column "street2", :string
    t.column "city", :string
    t.column "state", :string
    t.column "zip", :string
    t.column "phone", :string
    t.column "email", :string
    t.column "amount_paid", :integer, :default => 0
    t.column "payment_type_id", :integer
    t.column "stable", :string
    t.column "check_number", :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "payment_types", :force => true do |t|
    t.column "name", :string
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

  create_table "riders", :force => true do |t|
    t.column "name", :string
    t.column "owner_id", :integer
    t.column "created_at", :datetime, :null => false
    t.column "updated_at", :datetime, :null => false
  end

end
